default_json = "config/defaultJson.json"
json_path = "config/config.json"
config_path = "config/config.json"
user_dict_path = "config/userDict.json"
prefix_path = "config/prefixList.json"
about = "config/pub/about.txt"
help = "config/pub/help.txt"

## Key Paths
hashes = "config/prv/keys/hashes.json"
key_path = "config/prv/keys/"
nacl_keys = key_path + "nacl/"
aes256_keys = key_path + "aes256/"
fernet128_keys = key_path + "fernet128/"
chacha20_keys = key_path + "chacha20/"
x509_path = key_path + "TLS/"
